sp/chk precomp kernel 264
ROCmSoftwarePlatform/MIFin pull request #41
Opened 2022-02-08 02:41 UTC by technicalgrp89

Test precompiled kernel evaluation #264
Code review requested. @JehandadKhan

2022-02-08 15:37 UTC, JehandadKhan requested changes
I have pointed out a few issues in the code. Please beef up the test cases as well a single config might not be sufficient.
@JehandadKhan - Following are the some of the test input sample files @ /fin/src/tests folder.  
1. gfx900_56.kdb  gfx900_64.kdb  gfx906_60.kdb  gfx906_64.kdb  gfx90878.kdb

2022-03-14 22:41 UTC, cderb requested changes

2022-03-22 14:52 UTC, cderb requested changes

2022-04-05 17:56 UTC, cderb approved these changes

2022-04-07 18:58 UTC, JehandadKhan requested changes

2022-05-16 16:39 UTC, merged