[bg/LWPTUNA-173]
ROCmSoftwarePlatform/MIFin pull request #65
Opened 2022-09-28 21:50 UTC by bghimireamd

* Set layout from json
  * Add simple test for memory layout

2022-09-28 22:46 UTC, cderb approved these changes
LGTM

2022-09-30 18:11 UTC, alexandraBara requested changes

2022-10-04 15:46 UTC, JehandadKhan requested changes

2022-10-04 19:14 UTC, cderb requested changes

2022-10-05 19:07 UTC, alexandraBara approved these changes

2022-10-05 21:14 UTC, cderb approved these changes

2022-10-05 21:53 UTC, JehandadKhan approved these changes

2022-10-05 21:53 UTC, merged